# Generated by Django 4.1.1 on 2022-09-27 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.AddField(
            model_name='person',
            name='image_file',
            field=models.ImageField(null=True, upload_to='photos/male/age/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
