# Generated by Django 4.1.1 on 2022-09-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_generator', '0002_remove_person_photo_person_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_file',
            field=models.ImageField(upload_to='photos/male/age/%Y/%m/%d/'),
        ),
    ]
