# Generated by Django 4.1.1 on 2022-09-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_generator', '0003_alter_person_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image_file',
        ),
    ]
