# Generated by Django 4.1.1 on 2022-09-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_generator', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'gender', 'name', 'age']},
        ),
    ]
